trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  acrName: 'tailspinspacegame7904'         # ACR name only (not full login server)
  acrLoginServer: 'tailspinspacegame7904.azurecr.io'  # Full login server name

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: 'CICDPool'
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Build and Push Image using ACR'
      inputs:
        azureSubscription: 'Resource Manager - Tailspin - Space Game'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr build \
            --registry $(acrName) \
            --image $(webRepository):$(tag) \
            --file Tailspin.SpaceGame.Web/Dockerfile \
            .

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      name: 'CICDPool'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy from ACR'
      inputs:
        azureSubscription: 'Resource Manager - Tailspin - Space Game'
        appName: $(WebAppName)
        containers: $(acrLoginServer)/$(webRepository):$(tag)
